vec4:
	g++ -std=c++11 vec4test.cpp ../src/Vec4.cpp -I../include -o vec4test.out

vec3:
	g++ -std=c++11 vec3test.cpp ../src/Vec3.cpp -I../include -o vec3test.out

timer:
	g++ -std=c++11 timertest.cpp ../src/Timer.cpp -I../include -o timertest.out
	

clean:
	rm -f *.out
